### ISSUE TITLE
Connect issue

### ISSUE THREAD

**Issue by hackerjavahacker** [furious-monkey/musa-servey#2]
Database connect issue.

**Comment by furious-monkey** [comment]
Just fixed. Thanks.

**Comment by kingstar0126** [comment]
Still not connected. Require solution.

**Comment by furious-monkey** [comment]
Locate the MySQL Command-Line Client. ...
Run the client. ...
Enter your password. ...
Get a list of databases. ...
Create a database. ...
Select the database you want to use. ...
Create a table and insert data. ...
Finish working with the MySQL Command-Line Client.
